// All portfolio content is managed from this file.
// Update or add content here without changing the page structure.
const portfolio = {
  name: 'Eky Fernanda',
  role: 'Applied Data Science Student',
  email: 'ekyfernandasp@gmail.com',
  location: 'Surabaya, Jawa Timur, Indonesia',
  year: new Date().getFullYear(),

  profile: {
    kicker: 'AI/ML ENGINEER · DATA SCIENTIST · DATA ANALYST',
    headline: 'Turning data into <span class="gradient-text">meaningful insights.</span>',
    description: [
      'I\'m <strong>Eky Fernanda</strong>, an Applied Data Science professional focused on <strong>Data Science, Data Analytics, Artificial Intelligence, and Machine Learning</strong>. I transform data into meaningful insights and practical solutions for real-world problems.',
      'With experience in <strong>data analysis, visualization, dashboard development, machine learning, and IoT</strong>, I build data products from preparation through implementation. I also bring leadership, teamwork, and problem-solving skills, and am open to opportunities as a <strong>Data Scientist, Data Analyst, or AI/ML Engineer</strong>.',
    ],
    photo: 'photo_eky.png',
  },

  social: [
    ['LinkedIn', 'https://www.linkedin.com/in/eky-fernanda/'],
    ['GitHub', 'https://github.com/ffernandaeky'],
    ['Email', 'mailto:ekyfernandasp@gmail.com'],
  ],

  skills: {
    'Programming & Web': ['Python', 'R', 'HTML', 'CSS', 'JavaScript', 'MySQL'],
    'Data Analytics': ['Data Analysis', 'Data Visualization', 'Google Data Studio', 'Power BI', 'Tableau'],
    'Data Engineering': ['Dashboard Development', 'Grafana', 'ECharts', 'SQL'],
    'Professional Skills': ['Leadership', 'Communication', 'Teamwork', 'Problem Solving'],
  },

  projects: [
    {
      id: 'dashboard-tantangan-kerja-2022',
      title: 'Indonesia Employment Challenges Dashboard 2022',
      desc: 'A Power BI dashboard that maps employment challenges across Indonesian cities and regencies through TPT and TPAK clustering.',
      image: 'dashboard-tantangan-kerja.svg?v=20260802c',
      tags: ['Power BI', 'Python', 'K-Means', 'Data Analysis'],
      metric: 'Academic Project · Applied Statistics',
      problem: 'Data ketenagakerjaan antarwilayah perlu dirangkum menjadi kelompok yang mudah dibandingkan agar wilayah dengan tantangan kerja relatif tinggi dapat diidentifikasi dan dieksplorasi.',
      dataset: 'Data tahun 2022 dari 514 kabupaten/kota di Indonesia. Analisis berfokus pada Tingkat Pengangguran Terbuka (TPT) dan Tingkat Partisipasi Angkatan Kerja (TPAK), dengan atribut pendukung seperti persentase penduduk miskin, lama sekolah, IPM, dan PDRB.',
      method: 'Eksplorasi data dilakukan dengan statistik ringkasan, distribusi, boxplot, heatmap korelasi, dan peringkat TPT/TPAK. TPT (Tingkat Pengangguran Terbuka) adalah persentase angkatan kerja yang belum bekerja dan sedang mencari pekerjaan. TPAK (Tingkat Partisipasi Angkatan Kerja) adalah persentase penduduk usia kerja yang aktif dalam angkatan kerja, baik bekerja maupun mencari pekerjaan. K-Means kemudian diterapkan pada TPT dan TPAK; elbow method serta silhouette score digunakan untuk memilih jumlah klaster.',
      process: 'Memuat dan memeriksa data → menangani kualitas data → eksplorasi statistik dan visual → menentukan K optimal → membentuk klaster → memberi label karakteristik klaster → menyajikan hasil dalam dashboard Power BI.',
      result: 'K=3 dipilih sebagai jumlah klaster optimal dengan silhouette score tertinggi sekitar 0,467. Hasil pengelompokan terdiri dari 226 kabupaten/kota dengan tantangan tinggi, 246 sedang, dan 42 rendah.',
      tech: 'Power BI, Python, Pandas, NumPy, Matplotlib, Seaborn, scikit-learn',
      challenge: 'Menerjemahkan hasil klaster numerik menjadi kategori yang dapat dipahami pengguna dashboard. Label tinggi, sedang, dan rendah ditetapkan berdasarkan kombinasi TPT serta TPAK, bukan sebagai penilaian tunggal terhadap kondisi suatu wilayah.',
      lesson: 'Clustering membantu melihat pola relatif antarwilayah, sementara dashboard memungkinkan pengguna menelusuri hasil melalui peta, filter, dan ringkasan. Validasi jumlah klaster penting agar segmentasi tidak hanya bergantung pada asumsi awal.',
      role: 'Data Analyst & Dashboard Developer',
      caseFacts: [
        ['CAKUPAN', '514 kabupaten/kota', 'Data Indonesia 2022'],
        ['FOKUS', 'TPT & TPAK', 'Tantangan kerja wilayah'],
        ['MODEL', 'K-Means · K=3', 'Silhouette ≈ 0,467'],
      ],
      visualAlt: 'Ringkasan dashboard tantangan kerja Indonesia 2022',
      visualCaption: 'Ringkasan klaster tantangan kerja berdasarkan TPT dan TPAK.',
    },
    {
      id: 'quick-count-pilpres-2019',
      title: '2019 Presidential Quick Count: Central Kalimantan',
      desc: 'Vote-proportion estimation using random, cluster, and multistage sampling on Central Kalimantan’s 2019 presidential-election data.',
      image: 'quick-count-pilpres-2019.svg?v=20260802a',
      tags: ['Python', 'Statistical Sampling', 'Data Analysis'],
      metric: 'Academic Project · Applied Statistics',
      problem: 'Perhitungan cepat membutuhkan cara untuk mengestimasi proporsi suara dari sebagian data secara terukur. Proyek ini membandingkan beberapa pendekatan sampling untuk melihat kestabilan estimasi dan galatnya saat ukuran sampel bertambah.',
      dataset: 'Data Pilpres 2019 Kalimantan Tengah dengan cakupan 14 kabupaten/kota. Dataset diproses hingga tingkat kelurahan dan TPS, lalu digunakan untuk membentuk data simulasi suara pasangan calon 1, pasangan calon 2, dan golput.',
      method: 'Proyek menguji random sampling, cluster random sampling berdasarkan kabupaten/kota, kecamatan, dan kelurahan, serta multistage random sampling. Estimasi proporsi tiap kategori suara dibandingkan terhadap proporsi total untuk menghitung galat relatif.',
      process: 'Memuat data provinsi → menyiapkan data kabupaten/kota → membentuk data TPS simulasi → mengambil sampel pada beberapa ukuran → menghitung proporsi dan galat → membandingkan hasil antar-metode.',
      result: 'Pada eksperimen random sampling di notebook, sampel 90% menghasilkan total galat terendah sekitar 0,069%. Hasil ini menggambarkan bagaimana estimasi cenderung mendekati proporsi total ketika cakupan sampel meningkat.',
      tech: 'Python, Pandas, NumPy, Matplotlib, Seaborn',
      challenge: 'Menjaga struktur wilayah dalam data sekaligus membandingkan metode sampling secara adil. Karena suara TPS dibangkitkan secara acak dari total suara, hasil digunakan sebagai simulasi pembelajaran, bukan hasil resmi pemilu.',
      lesson: 'Pemilihan desain sampling memengaruhi kualitas estimasi. Mengamati galat pada berbagai ukuran sampel membantu menentukan cakupan sampel yang memadai sebelum menerapkan quick count pada data lapangan.',
      role: 'Data Analyst',
      caseFacts: [
        ['WILAYAH', 'Kalimantan Tengah', '14 kabupaten/kota'],
        ['PERIODE', 'Pilpres 2019', 'Data simulasi TPS'],
        ['METODE', '3 pendekatan', 'Random, cluster, multistage'],
      ],
      visualAlt: 'Ringkasan analisis quick count Pilpres 2019 Kalimantan Tengah',
      visualCaption: 'Ringkasan data suara simulasi dan metode sampling yang dievaluasi.',
      gallery: [
        ['quick-count-sampling.svg?v=20260802a', 'Desain sampling', 'Tiga strategi sampling yang dibandingkan untuk membentuk estimasi quick count.'],
        ['quick-count-error.svg?v=20260802a', 'Galat estimasi', 'Ilustrasi galat estimasi yang mengecil saat ukuran sampel meningkat; titik 90% adalah hasil eksperimen random sampling pada notebook.'],
      ],
    },
    {
      id: 'online-game-web-scraping',
      title: 'Online Game Analysis Using Web Scraping',
      desc: 'An exploration of 100 online games to understand active-player patterns, price, and their relationship through visualisation and linear regression.',
      image: 'online-game-web-scraping.svg?v=20260802a',
      tags: ['Python', 'Web Scraping', 'Data Analysis', 'Linear Regression'],
      metric: 'Academic Project · Data Processing',
      problem: 'Informasi popularitas dan harga game online tersebar di halaman web. Proyek ini merangkum data tersebut menjadi gambaran yang lebih mudah dibaca untuk membandingkan game, pola harga, dan jumlah pemain aktif.',
      dataset: 'Data hasil web scraping dari 100 game online, dengan lima variabel: ranking, judul game, harga, pemain saat ini, dan total pemain. Sampel mencakup 29 game gratis serta 71 game berbayar.',
      method: 'Data dieksplorasi menggunakan statistik deskriptif, boxplot, histogram, heatmap korelasi, dan grafik perbandingan pemain aktif. Regresi linear kemudian digunakan dengan harga sebagai prediktor dan jumlah pemain aktif sebagai variabel respons.',
      process: 'Melakukan web scraping → menyusun dataset → memeriksa statistik ringkasan → membuat visualisasi tiap variabel dan perbandingan antargame → menganalisis harga → membangun regresi linear.',
      result: 'Dari 100 game, rata-rata pemain aktif tercatat 31.159 dengan median 12.860. Counter-Strike: Global Offensive memiliki 930.741 pemain aktif. Model memperkirakan sekitar 168.691 pemain aktif untuk harga Rp200.000, sehingga hasilnya perlu dibaca sebagai estimasi berbasis pola sampel.',
      tech: 'Python, Pandas, Matplotlib, Seaborn, scikit-learn, Web Scraping',
      challenge: 'Distribusi pemain sangat timpang karena beberapa game populer memiliki pemain jauh lebih tinggi dari mayoritas game lain. Hal ini membuat interpretasi rata-rata dan prediksi regresi perlu dilakukan dengan hati-hati.',
      lesson: 'Visualisasi dan statistik ringkasan membantu menemukan ketimpangan data sebelum pemodelan. Harga saja tidak cukup untuk menjelaskan popularitas karena genre, status gratis, kualitas, dan komunitas juga dapat memengaruhi jumlah pemain.',
      role: 'Data Analyst',
      caseFacts: [
        ['DATASET', '100 game online', '5 variabel hasil scraping'],
        ['FOKUS', 'Harga → pemain aktif', 'Eksplorasi dan regresi'],
        ['TEMUAN', '29 game gratis', '71 game berbayar'],
      ],
      visualAlt: 'Dashboard analisis data game online hasil web scraping',
      visualCaption: 'Ringkasan pemain aktif teratas dan pendekatan regresi harga terhadap pemain aktif.',
    },
    {
      id: 'dki-air-pollution-regression',
      title: 'DKI Jakarta Air Pollution Linear Regression',
      desc: 'Analisis hubungan karbon monoksida (CO) dan nitrogen dioksida (NO₂) pada data kualitas udara DKI Jakarta tahun 2021.',
      image: 'air-pollution-regression-dki-2021-v3.svg?v=20260731e',
      tags: ['Python', 'Linear Regression', 'Data Analysis'],
      metric: 'Academic Project · 2021',
      problem: 'Data pengukuran kualitas udara perlu dirangkum menjadi analisis yang mudah dipahami agar pola pencemaran di DKI Jakarta dapat ditinjau dengan lebih jelas.',
      dataset: 'Dataset Indeks Standar Pencemaran Udara (ISPU) tahun 2021 dari Jakarta Open Data, data.jakarta.go.id. Dataset memuat 11 variabel: tanggal, PM10, PM2.5, SO₂, CO, O₃, NO₂, nilai maksimum, parameter kritis, kategori, dan lokasi pengukuran.',
      method: 'Regresi linear digunakan untuk memodelkan hubungan antar-pengukuran polutan. Pada grafik, CO berperan sebagai prediktor dan NO₂ sebagai variabel respons; regresi linear berganda diperkenalkan sebagai pendekatan pengembangan model dengan lebih dari satu prediktor.',
      process: 'Mengumpulkan data ISPU → meninjau variabel dan kategori kualitas udara → menyiapkan data → memvisualisasikan observasi CO–NO₂ beserta garis regresi → menginterpretasikan pola.',
      result: 'Garis regresi menunjukkan kecenderungan positif: ketika nilai CO meningkat, prediksi NO₂ juga cenderung meningkat. Namun, sebaran titik yang lebar dan beberapa pencilan mengindikasikan bahwa CO saja belum cukup untuk menjelaskan seluruh variasi NO₂.',
      tech: 'Python, Linear Regression, Data Analysis, Data Visualization',
      challenge: 'Menafsirkan hubungan antar-polutan tanpa melebih-lebihkan kemampuan model, karena setiap observasi masih bervariasi cukup jauh dari garis regresi.',
      lesson: 'Terdapat asosiasi positif antara CO dan NO₂ pada data 2021. Untuk penilaian kualitas udara yang lebih andal, model perlu memasukkan polutan lain serta dievaluasi dengan metrik performa. Grafik CO–NO₂ saja belum cukup untuk menentukan status keamanan udara.',
    },
    {
      id: 'obesity-level-classification',
      title: 'Obesity Level Classification with PyCaret',
      desc: 'An AutoML classification workflow that predicts obesity levels and packages the final pipeline for use in a Streamlit interface.',
      image: 'obesity-classification-automl.svg?v=20260802a',
      tags: ['Python', 'PyCaret', 'AutoML', 'Streamlit', 'LightGBM'],
      metric: 'Academic Project · MLOps',
      problem: 'Predicting obesity levels requires a repeatable machine learning workflow that can prepare data, compare candidate models, and provide a model ready for prediction.',
      dataset: 'An obesity classification dataset with NObeyesdad as the target label. The notebook prepares numerical data by filling missing values with column means before model training.',
      method: 'PyCaret Classification is used to set up the experiment, compare candidate classifiers, tune the best model, evaluate it interactively, and finalize the selected pipeline. The saved pipeline output uses a LightGBM classifier.',
      process: 'Load dataset → impute missing numerical values → set NObeyesdad as the target → compare models → tune the best model → evaluate and finalize it → save obesity_pipeline.pkl → connect the model to Streamlit.',
      result: 'The workflow produced a finalized and saved obesity classification pipeline (obesity_pipeline.pkl). This makes the trained pipeline reusable for prediction in the accompanying Streamlit interface.',
      tech: 'Python, Pandas, PyCaret, LightGBM, Streamlit',
      challenge: 'Keeping the prediction interface aligned with the features used in the trained dataset is essential. Input fields and column names must match the model pipeline before deployment.',
      lesson: 'AutoML shortens the experimentation cycle, but data quality, feature consistency, and evaluation remain essential before a model is used in an application.',
      role: 'Machine Learning Developer',
      caseFacts: [
        ['TARGET', 'NObeyesdad', 'Obesity-level class'],
        ['WORKFLOW', 'PyCaret AutoML', 'Compare and tune models'],
        ['OUTPUT', 'Saved pipeline', 'Streamlit-ready model'],
      ],
      visualAlt: 'Obesity level classification AutoML workflow',
      visualCaption: 'From data preparation and AutoML training to a reusable Streamlit prediction pipeline.',
    },
    {
      id: 'stroke-risk-classification',
      title: 'Stroke Risk Classification with PyCaret',
      desc: 'An AutoML workflow and Streamlit dashboard for exploring stroke-risk classification from patient health information.',
      image: 'stroke-risk-classification.svg?v=20260802a',
      tags: ['Python', 'PyCaret', 'AutoML', 'Streamlit', 'Plotly'],
      metric: 'Academic Project · MLOps',
      problem: 'Health information can be difficult to interpret consistently. This project builds a repeatable classification workflow to explore stroke-risk predictions from patient features.',
      dataset: 'The healthcare stroke dataset, with stroke as the target label. The preprocessing stage removes the record ID and fills missing numerical values with column means before model training.',
      method: 'PyCaret Classification sets up the experiment, compares candidate models, tunes the best model, evaluates it, and saves the final pipeline as stroke_pipeline. The Streamlit application sends user input to the saved pipeline and visualises age against average glucose level with Plotly.',
      process: 'Load healthcare dataset → remove ID column → impute missing values → set stroke as target → compare models → tune and evaluate the best model → finalize and save stroke_pipeline → build the Streamlit prediction interface.',
      result: 'The project produced a reusable stroke classification pipeline and an interactive Streamlit interface. The interface captures patient inputs, shows the predicted class, and displays a supporting age–glucose visualisation.',
      tech: 'Python, Pandas, PyCaret, Streamlit, Plotly',
      challenge: 'Medical classification data requires especially careful interpretation. The user interface must keep its input features consistent with training data, and the model output must not be presented as a clinical diagnosis.',
      lesson: 'AutoML can accelerate prototyping, but responsible health-related use still requires robust validation, attention to class imbalance and bias, and clinical review before any real-world decision support.',
      role: 'Machine Learning Developer',
      caseFacts: [
        ['TARGET', 'Stroke', 'Risk classification label'],
        ['WORKFLOW', 'PyCaret AutoML', 'Compare and tune models'],
        ['OUTPUT', 'Streamlit app', 'Interactive prediction UI'],
      ],
      visualAlt: 'Stroke risk classification workflow and dashboard',
      visualCaption: 'From patient feature inputs and AutoML training to an interactive Streamlit prediction interface.',
    },
    {
      id: 'stroke-prediction-model-comparison',
      title: 'Stroke Prediction Model Comparison',
      desc: 'A Data Mining project comparing five classification algorithms for stroke prediction using healthcare data.',
      image: 'stroke-model-comparison.svg?v=20260802a',
      tags: ['Python', 'scikit-learn', 'Data Mining', 'Classification', 'Seaborn'],
      metric: 'Academic Project · Data Mining',
      problem: 'Stroke prediction is a classification problem where several algorithms can produce different performance characteristics. This project compares baseline models using a consistent data-preparation and evaluation workflow.',
      dataset: 'The healthcare stroke dataset, using stroke as the target. The ID column is removed, missing BMI values are imputed with the mean, and categorical features are encoded with LabelEncoder.',
      method: 'The data is split into 80% training and 20% testing data. Logistic Regression, Random Forest, K-Nearest Neighbors, Gaussian Naive Bayes, and Decision Tree are trained and evaluated with accuracy, classification reports, confusion matrices, and heatmaps.',
      process: 'Load dataset → inspect data quality → impute BMI values → encode categorical features → separate features and target → split train/test data → train five classifiers → compare accuracy → inspect the Decision Tree.',
      result: 'Logistic Regression reached the highest recorded test accuracy at 93.93%, followed closely by Random Forest at 93.84%. KNN reached 93.44%, Decision Tree 91.19%, and Gaussian Naive Bayes 86.69%.',
      tech: 'Python, Pandas, scikit-learn, Seaborn, Matplotlib, Graphviz',
      challenge: 'Accuracy alone can be misleading for an imbalanced health dataset. Confusion matrices and classification reports are needed to understand how each model treats both classes; model outputs are not medical diagnoses.',
      lesson: 'A systematic comparison makes model trade-offs visible. Strong accuracy is useful, but class balance, recall, precision, validation design, and responsible interpretation are essential for health-related classification.',
      role: 'Data Mining Team Member',
      caseFacts: [
        ['DATASET', 'Healthcare stroke data', 'Target: stroke'],
        ['MODELS', '5 classifiers', 'Same train/test split'],
        ['BEST RESULT', '93.93%', 'Logistic Regression'],
      ],
      visualAlt: 'Stroke prediction classification model accuracy comparison',
      visualCaption: 'Test-set accuracy comparison across five stroke prediction classifiers.',
    },
    {
      id: 'data-extraction-etl-pipeline',
      title: 'Data Extraction & ETL Pipeline',
      desc: 'A collection of Python workflows for extracting data from files, APIs, websites, memory, and SQLite before building a simple news ETL pipeline.',
      image: 'data-extraction-etl-pipeline.svg?v=20260802a',
      tags: ['Python', 'Pandas', 'Web Scraping', 'SQLAlchemy', 'ETL'],
      metric: 'Academic Project · Data Engineering',
      problem: 'Data comes in many formats and locations. This project explores repeatable ways to collect structured data from files, APIs, websites, and databases, then prepare it for use.',
      dataset: 'The notebook works with agricultural CSV data, JSONPlaceholder JSON resources, Indonesia COVID-19 API data, website content, a GDP CSV source, user JSON data, an IMDb SQLite database, and BBC News headlines.',
      method: 'Extraction uses urllib, requests, CSV and JSON modules, Pandas, BeautifulSoup, and SQLAlchemy. The ETL example extracts BBC News headlines, transforms titles to uppercase, and loads the result into a SQLite table.',
      process: 'Download and parse CSV/JSON → request API data → scrape website lists and tables → read data in memory with StringIO → query SQLite with SQLAlchemy → extract news titles → transform text → load a news table into SQLite.',
      result: 'The notebook demonstrates several data-source patterns and completes an ETL workflow that stores transformed news headlines in a SQLite database. Each method produces structured output that can be explored with Python and Pandas.',
      tech: 'Python, Requests, urllib, Pandas, BeautifulSoup, SQLAlchemy, SQLite',
      challenge: 'Public web pages and APIs can change their structure or become unavailable. Extraction code needs validation, error handling, and clear assumptions about the source format.',
      lesson: 'Reliable data work starts with dependable extraction. Using the right parser and storage pattern for each source makes downstream analysis and automation more maintainable.',
      role: 'Data Engineering Student',
      caseFacts: [['SOURCES', '7+ source patterns', 'Files, API, web, database'], ['ETL', 'BBC News titles', 'Extract → transform → load'], ['OUTPUT', 'SQLite table', 'Structured news records']],
      visualAlt: 'Data extraction and ETL pipeline workflow',
      visualCaption: 'A workflow from multi-source extraction through transformation to a SQLite destination.',
    },
    {
      id: 'sumatra-rice-productivity-sur',
      title: 'Sumatra Rice Productivity SUR Analysis',
      desc: 'An econometric analysis of environmental factors affecting rice production in Sumatra using Seemingly Unrelated Regression (SUR), a method for estimating related regression equations together.',
      image: 'sumatra-rice-sur-analysis.svg?v=20260802a',
      tags: ['Python', 'Econometrics', 'SUR', 'Pandas', 'Statsmodels'],
      metric: 'Academic Project · Applied Econometrics',
      problem: 'Rice production is influenced by agricultural capacity and environmental conditions. This project models these relationships across Sumatra provinces while allowing two related production equations to be estimated as a system.',
      dataset: 'A panel-style dataset with 224 observations from 1993–2020. Variables include province, year, rice production, harvested area, rainfall, humidity, and average temperature.',
      method: 'Seemingly Unrelated Regression (SUR) is a system-regression method that estimates multiple related equations together when their error terms may be correlated. Exploratory distributions and a correlation heatmap are used before fitting a two-equation SUR system. Equation 1 models production with harvested area and rainfall; Equation 2 models production with humidity and average temperature. Estimation uses system GLS with robust covariance.',
      process: 'Load and inspect data → produce descriptive statistics → visualise variable distributions → inspect correlations → define two SUR equations → fit the system → interpret coefficients and p-values.',
      result: 'The fitted system reports McElroy’s R² of 0.6765. In Equation 1, harvested area has a positive, statistically significant coefficient of 3.7288 (p < 0.001). Rainfall, humidity, and average temperature are not statistically significant at the 5% level in their respective equations.',
      tech: 'Python, Pandas, Seaborn, Matplotlib, linearmodels, Statsmodels',
      challenge: 'Environmental variables can be correlated and their effects vary by context. Coefficients need to be interpreted as associations within the specified model, rather than proof of a causal effect.',
      lesson: 'SUR is useful when related equations may share information through their errors. Combining exploratory analysis with model diagnostics helps separate strong signals, such as harvested area, from variables with less certain effects.',
      role: 'Econometrics Analyst',
      caseFacts: [['COVERAGE', '224 observations', '1993–2020'], ['MODEL', '2-equation SUR', 'Robust system GLS'], ['KEY RESULT', 'Harvested area', 'β = 3.7288; p < 0.001']],
      visualAlt: 'Sumatra rice productivity SUR analysis summary',
      visualCaption: 'Two-equation SUR design and the key coefficient result for harvested area.',
    },
    {
      id: 'youtube-comment-sentiment-analysis',
      title: 'YouTube Comment Sentiment Analysis',
      desc: 'A text-mining analysis of audience reactions to a Tesla Cybertruck review using YouTube comments and VADER sentiment scoring.',
      image: 'youtube-comment-sentiment-analysis.svg?v=20260802a',
      tags: ['Python', 'NLP', 'YouTube API', 'NLTK', 'VADER'],
      metric: 'Academic Project · Text Mining',
      problem: 'Thousands of YouTube comments are difficult to review manually. This project turns audience responses to a Tesla Cybertruck review into a structured sentiment summary and highlights the words used most often in positive and negative comments.',
      dataset: '7,698 public top-level comments collected through the YouTube Data API from the video “Tesla Cybertruck Review: Already Iconic?”. After text cleaning, 7,623 comments were available for sentiment analysis.',
      method: 'Comments are lowercased, stripped of URLs, punctuation, numbers, stop words, and emojis, then tokenised and lemmatised with NLTK. VADER assigns a compound sentiment score; scores of zero or above are labelled positive and negative scores are labelled negative. CountVectorizer and WordCloud are used to explore frequent terms in each group.',
      process: 'Collect YouTube comments via API → save the raw data to CSV → clean and normalise text → remove stop words and lemmatise tokens → score sentiment with VADER → separate positive and negative comments → visualise word frequency, word clouds, and sentiment distribution.',
      result: 'Of 7,623 processed comments, 5,565 (73.00%) were classified as positive and 2,058 (27.00%) as negative. The result indicates that the analysed video received predominantly positive audience reactions within this rule-based sentiment-scoring setup.',
      tech: 'Python, Google API Client, Pandas, NLTK, VADER, scikit-learn, Matplotlib, Seaborn, WordCloud',
      challenge: 'Short online comments can contain sarcasm, slang, mixed sentiment, and context that a lexicon-based scorer may not capture. The notebook also uses a binary positive/negative threshold, so the output should be read as an automated indication rather than a complete interpretation of audience opinion.',
      lesson: 'A reproducible text-cleaning pipeline makes large comment collections easier to analyse. Pairing sentiment totals with word-frequency visuals helps explain the aggregate result, while still requiring careful interpretation of how language is used online.',
      role: 'Data Analyst',
      model: 'VADER sentiment scoring',
      caseFacts: [['SOURCE', 'YouTube comments', 'Tesla Cybertruck review'], ['SAMPLE', '7,623 comments', 'After text cleaning'], ['SENTIMENT', '73.00% positive', '5,565 of 7,623 comments']],
      visualAlt: 'YouTube comment sentiment analysis summary',
      visualCaption: 'Sentiment breakdown of the processed YouTube comments: 73.00% positive and 27.00% negative.',
      gallery: [
        ['youtube-comment-preprocessing.svg?v=20260802a', 'Text preprocessing pipeline', 'The cleaning steps used before VADER assigns each comment a sentiment label.'],
        ['youtube-comment-sentiment-distribution.svg?v=20260802a', 'Sentiment distribution', 'A readable comparison of the 5,565 positive and 2,058 negative comments.'],
      ],
    },
    {
      id: 'east-java-rainfall-pycaret',
      title: 'East Java Rainfall Forecasting & Classification with PyCaret',
      desc: 'A 7-day rainfall forecasting and intensity-classification workflow for 12 BMKG stations across East Java in 2024.',
      image: 'rainfall-pycaret-forecast.svg?v=20260802a',
      tags: ['Python', 'PyCaret', 'AutoML', 'Time Series', 'CatBoost'],
      metric: 'Academic Project · Machine Learning',
      problem: 'Daily rainfall observations from several stations need to be transformed into short-term forecasts and understandable intensity labels so the results can be reviewed consistently across locations.',
      dataset: 'BMKG station data from East Java in 2024, covering 12 stations with 366 observations per station. The workflow uses dates, station identifiers, rainfall, geographic coordinates, humidity, and an added air-pressure feature for modelling.',
      method: 'PyCaret Time Series runs a separate univariate forecasting experiment for each station, compares candidate models, tunes the selected model with MAE optimisation, and produces rolling 7-day forecasts. Forecast outputs are then labelled as no rain (≤4 mm), light (≤20 mm), moderate (≤50 mm), heavy (≤100 mm), or very heavy (>100 mm). PyCaret Classification compares and tunes classifiers for this intensity target.',
      process: 'Load data → add and position the air-pressure feature → inspect types, missing values, duplicates, geographic consistency, and correlations → split station time series → compare and tune forecasting models → forecast the next 7 days → assign rainfall-intensity labels → compare, tune, evaluate, and save classification models → prepare a map view of forecast results.',
      result: 'The notebook generated rolling 7-day forecasts for all 12 stations and saved the forecast dataset and trained model. Its overall tuned-forecast evaluation reports MAE 1.3406 and RMSE 1.6916. For intensity classification, CatBoost recorded the strongest listed mean cross-validation accuracy at 93.42%, followed by XGBoost at 93.22%.',
      tech: 'Python, Pandas, NumPy, PyCaret Time Series, PyCaret Classification, CatBoost, XGBoost, LightGBM, Matplotlib, Seaborn, Plotly',
      challenge: 'Rainfall data can contain zero values, missing values, and station-specific patterns. The pipeline cleans numerical values and evaluates each station separately, but forecast performance still needs to be interpreted alongside weather variability and the notebook’s validation design.',
      lesson: 'AutoML speeds up repeated experiments across station time series and classifiers, while a clear rainfall threshold makes the output easier to communicate. Accuracy and forecast metrics should be assessed per station and over future data before operational use.',
      role: 'Machine Learning Developer',
      model: 'PyCaret Time Series + CatBoost',
      caseFacts: [['COVERAGE', '12 BMKG stations', 'East Java, 2024'], ['FORECAST', '7 days', 'Rolling per station'], ['CLASSIFIER', 'CatBoost', '93.42% mean CV accuracy']],
      visualAlt: 'PyCaret rainfall forecasting and intensity classification workflow for East Java BMKG stations',
      visualCaption: 'PyCaret workflow: rolling 7-day forecasts for 12 stations, followed by five-category rainfall-intensity classification.',
      gallery: [
        ['rainfall-pycaret-models.svg?v=20260802a', 'Classifier comparison', 'CatBoost achieved the highest listed mean cross-validation accuracy in the notebook at 93.42%.'],
      ],
    },
    {
      id: 'east-java-rainfall-exponential-smoothing',
      title: 'East Java Rainfall Forecasting with Exponential Smoothing',
      desc: 'A station-level Exponential Smoothing workflow for 7-day rainfall forecasts and subsequent intensity classification in East Java.',
      image: 'rainfall-exponential-smoothing.svg?v=20260802a',
      tags: ['Python', 'Time Series', 'Exponential Smoothing', 'PyCaret', 'Data Visualization'],
      metric: 'Academic Project · Time Series',
      problem: 'Rainfall conditions vary across stations, making it useful to create a repeatable station-level process that forecasts the next seven days and turns rainfall values into categories that can be viewed geographically.',
      dataset: 'BMKG station data for East Java in 2024, covering 12 stations with 366 observations per station. The data includes daily rainfall, station name, date, geographic coordinates, humidity, and an air-pressure feature added during preparation.',
      method: 'The notebook cleans the station data, applies rolling per-row-group Exponential Smoothing to forecast seven future rainfall values for each station, and evaluates the forecasts using MAE, RMSE, MAPE, sMAPE, and R². The forecast output is classified into five rainfall-intensity thresholds, then PyCaret is used to compare, tune, evaluate, and save several classifiers.',
      process: 'Load and inspect data → add air-pressure feature → check missing values, duplicates, and geospatial consistency → explore distributions and time trends → run Exponential Smoothing by station → evaluate forecasts → save forecast output → define intensity classes → compare and tune classifiers → save final models → visualise intensity distribution and forecast map.',
      result: 'The notebook completed rolling 7-day forecasts for every station and saved the forecasting and classification outputs. It evaluates the time-series results with MAE, RMSE, MAPE, sMAPE, and R², and compares multiple classification candidates including Decision Tree, Gradient Boosting, XGBoost, CatBoost, Logistic Regression, Random Forest, LDA, LightGBM, and AdaBoost.',
      tech: 'Python, Pandas, NumPy, statsmodels Exponential Smoothing, PyCaret Classification, Matplotlib, Seaborn, Plotly, ipywidgets',
      challenge: 'Exponential Smoothing needs sufficient historical observations and can be sensitive to abrupt weather changes. The project applies a minimum history window and treats forecast accuracy as an evaluation question rather than assuming one model fits every station equally well.',
      lesson: 'A classical time-series baseline remains valuable alongside AutoML classification. Separating forecast generation, categorical interpretation, and map-based communication makes the workflow easier to inspect and reuse.',
      role: 'Data Scientist',
      model: 'Exponential Smoothing + PyCaret Classification',
      caseFacts: [['COVERAGE', '12 BMKG stations', 'East Java, 2024'], ['FORECAST', '7 days', 'Rolling per station'], ['OUTPUT', '5 intensity classes', 'Map-ready forecast results']],
      visualAlt: 'Exponential Smoothing rainfall forecasting workflow for East Java BMKG stations',
      visualCaption: 'From cleaned station observations to 7-day Exponential Smoothing forecasts and intensity classes.',
      gallery: [
        ['rainfall-exponential-smoothing-evaluation.svg?v=20260802a', 'Forecast-to-map workflow', 'The notebook connects cleaning, station-level forecasts, intensity labelling, classifier comparison, and geographic visualisation.'],
      ],
    },
    {
      id: 'youtube-agriculture-indobert',
      title: 'YouTube Agriculture: IndoBERT Topic Classification',
      desc: 'A full-stack platform that turns Indonesian agricultural YouTube content into structured data and classifies it into five practical farming topics.',
      image: 'youtube-agriculture-indobert.svg?v=20260802a',
      tags: ['Python', 'IndoBERT', 'NLP', 'Flask', 'Next.js', 'PostgreSQL'],
      metric: 'Final Project · Natural Language Processing',
      problem: 'Agricultural knowledge on YouTube is abundant but difficult to explore by topic. This project creates an end-to-end system that collects video metadata, processes Indonesian text, and assigns a relevant agricultural category so the content becomes easier to search and analyse.',
      dataset: 'The final training summary records 4,260 labelled Indonesian agricultural-video records. The data consists of video metadata together with titles and descriptions collected through the YouTube Data API. The label set is balanced across five topics: pest control, fertilising, irrigation, organic farming, and hydroponics.',
      method: 'The system retrieves video metadata using the YouTube Data API, then normalises Indonesian text by removing noise, URLs, mentions, punctuation, numbers, stop words, and repeated characters. Sastrawi stemming and a slang-normalisation dictionary prepare the text for IndoBERT. The IndoBERT base model is fine-tuned for five-class classification; model selection uses the average of test F1 score and accuracy.',
      process: 'Manage agriculture keywords → scrape unique YouTube videos by topic → store metadata in PostgreSQL → combine title and description → clean, normalise, remove stop words, and stem Indonesian text → label topics → stratify train, test, and evaluation data → fine-tune IndoBERT over candidate epoch settings → select the best model → save predictions and reports → serve the workflow through Flask APIs and a Next.js dashboard.',
      result: 'The final saved training summary selected the run with a maximum of 6 epochs and its best inner epoch at 3. On 426 held-out evaluation records, the model achieved 90.14% accuracy, 90.33% weighted precision, and 89.98% weighted F1. The platform also provides topic-based exploration, keyword management, data processing, model reporting, and direct video classification.',
      tech: 'Python, Flask, PostgreSQL, YouTube Data API, NLTK, Sastrawi, PyTorch, Hugging Face Transformers, IndoBERT, Next.js, TypeScript',
      challenge: 'Indonesian YouTube metadata can be noisy, informal, and mixed with non-agricultural language. The pipeline uses topic-specific validation terms, text normalisation, stop words, and relevance checks, but ambiguous descriptions and uneven vocabulary still require careful model evaluation and review.',
      lesson: 'A useful NLP application needs more than a trained model: data collection, reproducible preprocessing, well-defined labels, database storage, model reports, and an accessible interface all make the output more reliable and usable.',
      role: 'Full-Stack Machine Learning Developer',
      model: 'Fine-tuned IndoBERT · 5 classes',
      caseFacts: [['DATASET', '4,260 videos', 'Five balanced topic classes'], ['MODEL', 'Fine-tuned IndoBERT', 'Indonesian text classification'], ['EVALUATION', '90.14% accuracy', '426 held-out records']],
      visualAlt: 'YouTube Agriculture IndoBERT classification platform workflow',
      visualCaption: 'The platform connects YouTube data collection, Indonesian-language preprocessing, five-topic classification, and a dashboard.',
      gallery: [
        ['youtube-agriculture-model-evaluation.svg?v=20260802a', 'Final model evaluation', 'The selected IndoBERT model achieved 90.14% evaluation accuracy and 89.98% weighted F1 across 426 held-out records.'],
      ],
    },
    {
      id: 'pt-pal-ecw-crane-monitoring',
      title: 'ECW Crane Monitoring Dashboard',
      desc: 'A semi-real-time Grafana dashboard for monitoring ECW Crane availability, working time, efficiency, and machine-status trends at PT PAL Indonesia.',
      image: 'assets/pt-pal/ecw-crane-dashboard-v2.svg',
      tags: ['Grafana', 'PostgreSQL', 'SQL', 'ECharts', 'IoT'],
      metric: 'Professional Experience · PT PAL Indonesia',
      caseLayout: 'dashboard',
      problem: 'Operational ECW Crane data from an IoT module needed to be converted from raw SQL records into a clear monitoring view so relevant teams could review machine use and status more quickly.',
      dataset: 'IoT operational records for the ECW Crane stored in PostgreSQL. The source contains 406,000 rows and six fields, including timestamp, machine code, power status, working status, and accumulated power time.',
      method: 'The dashboard uses SQL queries and Grafana panels to calculate current-day totals, machine efficiency, power-versus-working time, status by cluster, and historical time-series patterns. ECharts enriches the visual presentation.',
      process: 'Receive SQL source → load into PostgreSQL → analyse data fields and monitoring needs → design Grafana panels → build queries and ECharts visualisations → present, evaluate, and publish to the server.',
      result: 'The completed dashboard provides filterable, semi-real-time views of machine status, usage duration, efficiency, and time-of-day patterns to support operational monitoring.',
      tech: 'Grafana, PostgreSQL, SQL, Apache ECharts, Industrial IoT data',
      challenge: 'The recorded counters are cumulative, so daily values need to be derived carefully from the latest and preceding records. The dashboard also distinguishes a powered-on machine from a machine that is actively working.',
      lesson: 'Combining well-defined operational metrics with historical and clustered views makes IoT data substantially easier to inspect and act on.',
      role: 'Data Analyst & Dashboard Developer',
      model: 'Grafana monitoring dashboard',
      caseFacts: [['SOURCE', '406,000 records', 'ECW Crane IoT module'], ['FOCUS', 'Availability & efficiency', 'Semi-real-time monitoring'], ['OUTPUT', 'Grafana + ECharts', 'Filterable operational views']],
      visualAlt: 'ECW Crane monitoring dashboard at PT PAL Indonesia',
      visualCaption: 'Overview of ECW Crane efficiency and operational-time monitoring panels.',
    },
    {
      id: 'pt-pal-fanuc-machine-monitoring',
      title: 'Fanuc Machine Monitoring Dashboard',
      desc: 'A Grafana dashboard that turns Fanuc machine records into semi-real-time operational, efficiency, and time-based monitoring views.',
      image: 'assets/pt-pal/fanuc-dashboard-v2.svg',
      tags: ['Grafana', 'PostgreSQL', 'SQL', 'ECharts', 'IoT'],
      metric: 'Professional Experience · PT PAL Indonesia',
      caseLayout: 'dashboard',
      problem: 'Fanuc machine data needed an informative, accessible dashboard so the relevant PT PAL Indonesia team could monitor utilisation and effectiveness without manually reviewing raw records.',
      dataset: 'Operational data from the Fanuc machine system, integrated into PostgreSQL for dashboard querying and visualisation. The dashboard supports date, time, duration, and cluster filters.',
      method: 'Grafana panels calculate the latest monitoring time, power time, working time, on-and-working time, idle time, off time, and efficiency. Historical charts and ECharts panels add time-series and clustered analysis.',
      process: 'Analyse available machine data → prepare PostgreSQL tables → define dashboard filters and KPIs → write SQL queries → build Grafana and ECharts panels → evaluate with stakeholders → publish the dashboard.',
      result: 'The dashboard brings together current operational indicators and historical machine patterns, enabling users to compare machine use across time windows and status clusters.',
      tech: 'Grafana, PostgreSQL, SQL, Apache ECharts, IoT data',
      challenge: 'A machine can be powered on but not working, so the dashboard needs separate calculations and labels for each state to avoid misleading efficiency interpretation.',
      lesson: 'Separating machine states, then pairing summary KPIs with historical charts, provides a more useful operational story than a single availability metric.',
      role: 'Data Analyst & Dashboard Developer',
      model: 'Grafana monitoring dashboard',
      caseFacts: [['SOURCE', 'Fanuc machine data', 'PostgreSQL integration'], ['FOCUS', 'Usage & efficiency', 'Semi-real-time monitoring'], ['VIEWS', 'Time & cluster filters', 'Grafana + ECharts']],
      visualAlt: 'Fanuc machine monitoring dashboard at PT PAL Indonesia',
      visualCaption: 'Fanuc dashboard overview with efficiency, operational-time, and historical monitoring panels.',
    },
    {
      id: 'pt-pal-compressor-monitoring',
      title: 'Ingersoll Rand Compressor Monitoring Dashboard',
      desc: 'A monitoring dashboard for Niaga Ingersoll Rand compressors that combines runtime, loading, pressure, temperature, pH, and efficiency indicators.',
      image: 'assets/pt-pal/compressor-dashboard-v2.svg',
      tags: ['Grafana', 'PostgreSQL', 'SQL', 'ECharts', 'Industrial IoT'],
      metric: 'Professional Experience · PT PAL Indonesia',
      caseLayout: 'dashboard',
      problem: 'Compressor operations require visibility into both runtime and condition measurements so teams can monitor performance and quickly investigate potentially abnormal machine behaviour.',
      dataset: 'Niaga Ingersoll Rand Compressor operational records supplied in SQL format, then loaded into PostgreSQL to support Grafana queries and semi-real-time visualisation.',
      method: 'The dashboard presents latest monitoring time, daily power, working and loading time, air-discharge temperature, pack-discharge pressure, pH growth, average pH, and efficiency. Historical panels provide broader trend analysis.',
      process: 'Review SQL source → load data into PostgreSQL → identify operational and condition metrics → design dashboard sections → implement Grafana queries and ECharts panels → evaluate and upload to the server.',
      result: 'The finished dashboard provides a consolidated operational view with condition-focused charts, making it easier to review compressor trends and investigate overheat signals.',
      tech: 'Grafana, PostgreSQL, SQL, Apache ECharts, Industrial IoT data',
      challenge: 'Some counter-based measures are cumulative; the current-day value is therefore calculated from the difference between the newest record and an earlier record.',
      lesson: 'A monitoring dashboard becomes more actionable when operating time is paired with condition variables such as temperature and pressure.',
      role: 'Data Analyst & Dashboard Developer',
      model: 'Grafana monitoring dashboard',
      caseFacts: [['ASSET', 'Ingersoll Rand compressor', 'Niaga division'], ['FOCUS', 'Runtime & condition', 'Temperature, pressure, pH'], ['OUTPUT', 'Grafana + ECharts', 'Semi-real-time monitoring']],
      visualAlt: 'Ingersoll Rand Compressor monitoring dashboard at PT PAL Indonesia',
      visualCaption: 'Compressor overview showing duration, pressure, temperature, and efficiency panels.',
    },
    {
      id: 'pt-pal-employee-demographics',
      title: 'PT PAL Employee Demographics Dashboard',
      desc: 'An interactive dashboard for exploring PT PAL Indonesia employee demographics by age, gender, marital status, education, division, and employment type.',
      image: 'assets/pt-pal/employee-demographics-dashboard-v2.svg',
      tags: ['Grafana', 'PostgreSQL', 'SQL', 'ECharts', 'HR Analytics'],
      metric: 'Professional Experience · PT PAL Indonesia',
      caseLayout: 'dashboard',
      problem: 'Employee demographic information needed to be presented in a more accessible form so Human Capital Management could review workforce composition without navigating raw database tables.',
      dataset: 'PT PAL Indonesia employee demographic records, imported from SQL into PostgreSQL. The dashboard supports gender, division, and employment-type filters.',
      method: 'Grafana and ECharts are used to visualise employee age distribution, total employees, average age, gender status, marital status by age, education composition, and age distribution by education level.',
      process: 'Prepare SQL data → load it into PostgreSQL → inspect demographic fields → define filters and HR metrics → design and build dashboard panels → evaluate the dashboard → deploy to the server.',
      result: 'The dashboard provides a filterable, semi-real-time demographic overview that supports faster workforce mapping and exploratory analysis for the Human Capital Management division.',
      tech: 'Grafana, PostgreSQL, SQL, Apache ECharts, HR analytics',
      challenge: 'The dashboard must keep the demographic breakdowns understandable while allowing users to slice the data by several workforce attributes.',
      lesson: 'Clear, interactive demographic visuals make workforce data easier to interpret and can support more focused HR discussions.',
      role: 'Data Analyst & Dashboard Developer',
      model: 'Grafana HR analytics dashboard',
      caseFacts: [['DOMAIN', 'Human Capital Management', 'PT PAL Indonesia'], ['FILTERS', 'Gender, division, type', 'Interactive exploration'], ['OUTPUT', 'Grafana + ECharts', 'Employee demographic mapping']],
      visualAlt: 'PT PAL Indonesia employee demographics dashboard',
      visualCaption: 'Demographic overview covering workforce composition and age distribution.',
    },
    {
      id: 'pt-pal-guest-book-dashboard',
      title: 'PT PAL Digital Guest Book Dashboard',
      desc: 'A Grafana dashboard that transforms digital guest-book records into timely views of visits, categories, agencies, destinations, and divisional activity.',
      image: 'assets/pt-pal/guest-book-dashboard-v2.svg',
      tags: ['Grafana', 'PostgreSQL', 'SQL', 'ECharts', 'Data Visualization'],
      metric: 'Professional Experience · PT PAL Indonesia',
      caseLayout: 'dashboard',
      problem: 'Guest-book information was stored across related records and needed a concise dashboard for reviewing arrivals, visit categories, agencies, destinations, and visit history.',
      dataset: 'A PostgreSQL guest-book database with related categories, divisions, employees, and guest tables. Guest records include visitor name, purpose, category, agency, description, and arrival date.',
      method: 'SQL joins connect the relational data, then Grafana and ECharts visualise the latest data date, daily arrivals, visits by category, agencies and destination divisions, descriptions, historical trends, top agencies, and division statistics.',
      process: 'Review SQL tables → model relationships in PostgreSQL → define guest-book metrics and filters → build Grafana queries and ECharts panels → present and evaluate → deploy to the server.',
      result: 'The completed dashboard provides a clear, filterable view of guest arrivals and visit patterns, including historical and division-level analysis.',
      tech: 'Grafana, PostgreSQL, SQL, Apache ECharts, relational database design',
      challenge: 'The data is distributed across several relational tables, so reliable joins and consistent category/division definitions are essential for accurate totals and breakdowns.',
      lesson: 'A well-structured relational model allows administrative records to become practical monitoring data when paired with focused visualisations.',
      role: 'Data Analyst & Dashboard Developer',
      model: 'Grafana operational dashboard',
      caseFacts: [['DOMAIN', 'Guest-book operations', 'Human Capital Management'], ['DATA MODEL', '4 related tables', 'Guest, employee, division, category'], ['OUTPUT', 'Grafana + ECharts', 'Visits and historical insights']],
      visualAlt: 'PT PAL Indonesia digital guest book dashboard',
      visualCaption: 'Guest-book overview with daily arrivals, categories, agencies, and destination divisions.',
    },
  ],

  experience: [
    {
      section: 'Professional Experience',
      items: [
        { period: 'Jan 2025 – May 2025', position: 'Data Analyst Intern', organization: 'PT PAL Indonesia', description: 'Developed semi-real-time monitoring dashboards to visualize machine performance and operational data using Grafana and Apache ECharts. Partnered with engineers to analyze production data from ECW Cranes, Fanuc machines, and Ingersoll Rand compressors, transforming raw operational information into interactive dashboards. The work improved data accessibility and helped engineers monitor equipment performance more efficiently.', skills: ['Grafana', 'Apache ECharts', 'Dashboard Development', 'Industrial Data Analysis', 'Data Visualization', 'SQL'] },
        { period: 'Aug 2025 – Nov 2025', position: 'Data Science Intern', organization: 'BMKG – Stasiun Meteorologi Maritim Tanjung Perak Surabaya', description: 'Assisted in collecting, processing, and analyzing meteorological data to support daily weather observation and reporting activities. Worked with environmental datasets to identify trends, organize weather information, and contribute to operational reports used by the meteorological team. This internship strengthened analytical thinking, data-processing skills, and practical experience with real-world environmental data.', skills: ['Python', 'Data Analysis', 'Meteorological Data', 'Data Processing', 'Statistics', 'Research'] },
      ],
    },
    {
      section: 'Achievements',
      items: [
        { position: 'Google Data Studio', description: 'Completed professional training focused on designing interactive dashboards and transforming raw datasets into meaningful business insights using Google Data Studio. Learned dashboard optimization, visualization best practices, and interactive reporting techniques for business analytics.', skills: ['Dashboard', 'Google Data Studio', 'Business Intelligence', 'Visualization'] },
        { position: 'Microsoft Power BI', description: 'Completed intensive Microsoft Power BI training covering data preparation, transformation, modeling, visualization, and dashboard development. Built interactive reports that present complex business information as clear, meaningful insights for decision-making.', skills: ['Power BI', 'Data Modeling', 'Dashboard', 'Power Query', 'Business Intelligence'] },
        { position: 'Tableau', description: 'Completed Tableau training with an emphasis on visual analytics, dashboard storytelling, and business reporting. Learned to transform raw datasets into interactive dashboards that communicate insights clearly and support strategic decision-making.', skills: ['Tableau', 'Data Visualization', 'Dashboard', 'Analytics'] },
        { position: 'JavaScript', description: 'Successfully completed JavaScript training covering programming fundamentals, DOM manipulation, asynchronous programming, and modern web-development concepts. Strengthened programming skills for developing interactive and responsive web applications.', skills: ['JavaScript', 'DOM', 'Web Development', 'Programming'] },
      ],
    },
    {
      section: 'Leadership & Organization',
      items: [
        { position: 'Chairman', organization: 'HIMIT PENS 2025', description: 'Led the Informatics Student Association by planning organizational strategies, coordinating executive board members, supervising annual work programs, and ensuring collaboration across divisions. Represented the organization in institutional meetings while fostering teamwork, leadership, communication, and problem-solving throughout organizational activities.', skills: ['Leadership', 'Management', 'Public Speaking', 'Team Coordination', 'Strategic Planning'] },
        { position: 'Project Coordinator', organization: 'PKKMB × Technogear PENS 2024', description: 'Designed the overall event concept and coordinated multiple committees throughout the planning and execution phases. Managed timelines, participant activities, and event workflows while ensuring all programs were delivered successfully according to objectives and schedules.', skills: ['Project Management', 'Leadership', 'Coordination', 'Event Planning', 'Teamwork'] },
        { position: 'Project Coordinator', organization: 'Dynamic Outbound HIMIT PENS 2024', description: 'Led the conceptual planning and execution of Dynamic Outbound HIMIT PENS 2024 by developing activity concepts, coordinating committee members, and aligning delivery with organizational goals. Collaborated with multiple divisions to create engaging programs that strengthened teamwork and leadership among participants.', skills: ['Leadership', 'Coordination', 'Communication', 'Project Planning', 'Team Building'] },
        { position: 'Committee Member', organization: 'KPU HIMIT PENS 2023', description: 'Supported organizational election activities by coordinating administrative processes, assisting event operations, and helping ensure the smooth execution of election programs. Worked collaboratively with committee members to maintain an organized, transparent, and successful election process.', skills: ['Committee', 'Administration', 'Coordination', 'Communication'] },
        { position: 'Junior Staff', organization: 'HIMIT PENS 2024', description: 'Actively contributed to organizational programs by supporting departmental activities, committee events, and student development initiatives. Collaborated with senior members in planning and executing programs while developing leadership, teamwork, organizational management, and communication skills.', skills: ['Teamwork', 'Leadership', 'Organization', 'Communication'] },
      ],
    },
    {
      section: 'Participation',
      items: [
        { position: 'LKMM Participant', description: 'Participated in Student Leadership and Management Training (LKMM), focusing on leadership development, teamwork, communication, organizational management, and decision-making. The program combined collaborative learning activities with practical case studies to build confidence in working through organizational challenges.', skills: ['Leadership', 'Teamwork', 'Communication', 'Problem Solving'] },
      ],
    },
  ],
};
